name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true

jobs:
  release:
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Run tests
        run: pytest -v

      - name: Merge release into main
        run: |
          git checkout main
          git merge origin/release
          git push origin main

      - name: Merge release into develop
        run: |
          git checkout develop
          git merge origin/release
          git push origin develop

      - name: Create and push tag
        run: |
          git checkout main
          if ! git rev-parse v${{ github.event.inputs.version }} >/dev/null 2>&1; then
            git tag -a v${{ github.event.inputs.version }} -m "Release ${{ github.event.inputs.version }}"
            git push origin v${{ github.event.inputs.version }}
          else
            echo "Tag v${{ github.event.inputs.version }} already exists. Skipping tag creation."
          fi

      - name: Update Homebrew Tap
        env:
          TAP_REPO_TOKEN: ${{ secrets.PAT }}
        run: |
          git clone https://x-access-token:${TAP_REPO_TOKEN}@github.com/${{ github.repository_owner }}/homebrew-tap.git
          cd homebrew-tap

          NEW_VERSION="${{ github.event.inputs.version }}"
          NEW_SHA256=$(curl -sL https://github.com/qlmmlp/codeshuttle/archive/refs/tags/v${NEW_VERSION}.tar.gz | sha256sum | awk '{print $1}')

          FORMULA_FILE="Formula/codeshuttle.rb"

          # Update the formula file with the new version and SHA256
          sed -e "s/version \".*\"/version \"${NEW_VERSION}\"/" \
              -e "s/sha256 \".*\"/sha256 \"${NEW_SHA256}\"/" \
              -e "s#url \".*\"#url \"https://github.com/qlmmlp/codeshuttle/archive/refs/tags/v${NEW_VERSION}.tar.gz\"#" \
              "$FORMULA_FILE" > "$FORMULA_FILE.tmp" && mv "$FORMULA_FILE.tmp" "$FORMULA_FILE"

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add $FORMULA_FILE
          git commit -m "Update codeshuttle to ${{ github.event.inputs.version }}"
          git push

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          gh release create v${{ github.event.inputs.version }} \
            --title "Release ${{ github.event.inputs.version }}" \
            --notes-file CHANGELOG.md